f = open('extension/popup/popup.js', 'w', encoding='utf-8')
f.write('const STORAGE_KEY = "tl_stats";\n')
f.write('function getWeekStart() { const now = new Date(); const day = now.getDay(); return new Date(now.setDate(now.getDate() - day)).toDateString(); }\n')
f.write('function getStats() { return new Promise((resolve) => { chrome.storage.local.get([STORAGE_KEY], (result) => { resolve(result[STORAGE_KEY] || { scanned: 0, flagged: 0, correct: 0, categories: {}, weekStart: getWeekStart() }); }); }); }\n')
f.write('function renderStats(stats) {\n')
f.write('  const flagRate = stats.scanned > 0 ? Math.round((stats.flagged / stats.scanned) * 100) : 0;\n')
f.write('  document.getElementById("total-scanned").textContent = stats.scanned;\n')
f.write('  document.getElementById("total-flagged").textContent = stats.flagged;\n')
f.write('  document.getElementById("total-correct").textContent = stats.correct;\n')
f.write('  document.getElementById("flag-rate").textContent = flagRate + "%";\n')
f.write('  const catList = document.getElementById("category-list");\n')
f.write('  const cats = stats.categories || {};\n')
f.write('  const entries = Object.entries(cats).sort((a, b) => b[1] - a[1]);\n')
f.write('  if (entries.length === 0) { catList.innerHTML = "<div class=empty>No flags yet this week</div>"; return; }\n')
f.write('  const max = entries[0][1];\n')
f.write('  catList.innerHTML = entries.map(function(e) { var cat=e[0],count=e[1],pct=Math.round((count/max)*100); return "<div class=category-row><span class=category-name>"+cat+"</span><div class=category-bar-wrap><div class=category-bar style=\\"width:"+pct+"%\\"></div></div><span class=category-count>"+count+"</span></div>"; }).join("");\n')
f.write('}\n')
f.write('document.getElementById("reset-btn").addEventListener("click", function() { chrome.storage.local.set({ [STORAGE_KEY]: { scanned: 0, flagged: 0, correct: 0, categories: {}, weekStart: getWeekStart() } }, function() { renderStats({ scanned: 0, flagged: 0, correct: 0, categories: {} }); }); });\n')
f.write('getStats().then(renderStats);\n')
f.close()
print('Done')
